// Physically-based rendering with image-based lighting (glTF reference model).
// Binding convention (DESIGN §4):
//   vertex  { position, normal, texCoord } -> @location(0,1,2)
//   uniforms (one std140 UBO)              -> @group(0) @binding(0)
//   textures { diffuseEnv, specularEnv, brdfLUT } -> @group(1) @binding(0..2)
//   samplers { envSamp, lutSamp }                 -> @group(1) @binding(3..4)
//
// Simplifications vs. the old gallery shader (documented):
//  - The base-color / normal / metallic-roughness maps were solid 1x1 textures
//    in the original, so we fold them into scalar uniforms and skip the screen-
//    space tangent-frame trick (WGSL has no dFdx in this terse path); the
//    geometric normal is used directly.
//  - The specular env cube here is a single mip chain auto-generated by Beam
//    (mips:true) rather than the pre-filtered 10-level chain the original
//    streamed face-by-face; roughness still drives the sampled LOD so the
//    reflection blurs plausibly with roughness.

const M_PI = 3.141592653589793;
const MIN_ROUGHNESS = 0.04;
const SPEC_MIP_COUNT = 8.0;

struct Uniforms {
  cameraPos     : vec3f,
  metallic      : f32,
  modelMat      : mat4x4f,
  mvpMat        : mat4x4f,
  baseColor     : vec4f,
  lightDir      : vec3f,
  roughness     : f32,
  lightColor    : vec3f,
  lightStrength : f32,
};
@group(0) @binding(0) var<uniform> u : Uniforms;

@group(1) @binding(0) var diffuseEnv  : texture_cube<f32>;
@group(1) @binding(1) var specularEnv : texture_cube<f32>;
@group(1) @binding(2) var brdfLUT     : texture_2d<f32>;
@group(1) @binding(3) var envSamp     : sampler;
@group(1) @binding(4) var lutSamp     : sampler;

struct VsOut {
  @builtin(position) pos      : vec4f,
  @location(0)       worldPos : vec3f,
  @location(1)       normal   : vec3f,
};

@vertex
fn vs(
  @location(0) position : vec3f,
  @location(1) normal   : vec3f,
  @location(2) texCoord : vec2f,
) -> VsOut {
  var out : VsOut;
  let world = u.modelMat * vec4f(position, 1.0);
  out.worldPos = world.xyz / world.w;
  out.normal = normalize((u.modelMat * vec4f(normal, 0.0)).xyz);
  out.pos = u.mvpMat * vec4f(position, 1.0);
  return out;
}

// Fresnel (Schlick)
fn fresnel(r0 : vec3f, r90 : vec3f, VdotH : f32) -> vec3f {
  return r0 + (r90 - r0) * pow(clamp(1.0 - VdotH, 0.0, 1.0), 5.0);
}

// Smith geometric occlusion
fn geomOcclusion(NdotL : f32, NdotV : f32, alpha : f32) -> f32 {
  let r = alpha;
  let aL = 2.0 * NdotL / (NdotL + sqrt(r * r + (1.0 - r * r) * (NdotL * NdotL)));
  let aV = 2.0 * NdotV / (NdotV + sqrt(r * r + (1.0 - r * r) * (NdotV * NdotV)));
  return aL * aV;
}

// GGX microfacet distribution
fn microfacetDist(NdotH : f32, alpha : f32) -> f32 {
  let a2 = alpha * alpha;
  let f = (NdotH * a2 - NdotH) * NdotH + 1.0;
  return a2 / (M_PI * f * f);
}

fn iblContribution(
  perceptualRoughness : f32,
  NdotV : f32,
  n : vec3f,
  reflection : vec3f,
  diffuseColor : vec3f,
  specularColor : vec3f,
) -> vec3f {
  let lod = perceptualRoughness * SPEC_MIP_COUNT;
  let brdf = textureSample(brdfLUT, lutSamp, vec2f(NdotV, 1.0 - perceptualRoughness)).rg;
  let diffuseLight = textureSample(diffuseEnv, envSamp, n).rgb;
  let specularLight = textureSampleLevel(specularEnv, envSamp, reflection, lod).rgb;

  let diffuse = diffuseLight * diffuseColor;
  let specular = specularLight * (specularColor * brdf.x + brdf.y);
  return diffuse + specular;
}

@fragment
fn fs(in : VsOut) -> @location(0) vec4f {
  let perceptualRoughness = clamp(u.roughness, MIN_ROUGHNESS, 1.0);
  let metallic = clamp(u.metallic, 0.0, 1.0);
  let alpha = perceptualRoughness * perceptualRoughness;

  let f0 = vec3f(0.04);
  let diffuseColor = u.baseColor.rgb * (vec3f(1.0) - f0) * (1.0 - metallic);
  let specularColor = mix(f0, u.baseColor.rgb, metallic);

  let reflectance = max(max(specularColor.r, specularColor.g), specularColor.b);
  let r90 = vec3f(clamp(reflectance * 25.0, 0.0, 1.0));
  let r0 = specularColor;

  let n = normalize(in.normal);
  let v = normalize(u.cameraPos - in.worldPos);
  let reflection = -normalize(reflect(v, n));

  let l = normalize(u.lightDir);
  let h = normalize(l + v);

  let NdotL = clamp(dot(n, l), 0.001, 1.0);
  let NdotV = clamp(abs(dot(n, v)), 0.001, 1.0);
  let NdotH = clamp(dot(n, h), 0.0, 1.0);
  let VdotH = clamp(dot(v, h), 0.0, 1.0);

  let F = fresnel(r0, r90, VdotH);
  let G = geomOcclusion(NdotL, NdotV, alpha);
  let D = microfacetDist(NdotH, alpha);

  let diffuseContrib = (1.0 - F) * (diffuseColor / M_PI);
  let specContrib = F * G * D / (4.0 * NdotL * NdotV);

  var color = NdotL * u.lightColor * u.lightStrength * (diffuseContrib + specContrib);
  color += iblContribution(perceptualRoughness, NdotV, n, reflection, diffuseColor, specularColor);

  // Gamma correct (the env maps are sampled as sRGB, lit in linear).
  return vec4f(pow(color, vec3f(1.0 / 2.2)), u.baseColor.a);
}
